const router = require('express').Router();
const Authcontroller = require('./controllers/auth-controller');
const ActivateController = require('./controllers/activate-controller');
const authMiddlewares = require('./middlewares/auth-middlewares');
router.post('/api/send-otp',Authcontroller.sendOtp);
router.post('/api/verify-otp',Authcontroller.verifyOtp);
router.post('/api/activate',authMiddlewares,ActivateController.activate);
router.get('/api/refresh',Authcontroller.refresh);
router.post('/api/logout',authMiddlewares,Authcontroller.logout);
module.exports = router;